apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: posts-service
    app.kubernetes.io/component: posts-service
    app.kubernetes.io/instance: posts-service
    app.kubernetes.io/part-of: flo101
  name: posts-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: posts-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: posts-service
        deploymentconfig: posts-service
    spec:
      containers:
      - image: flo101/posts-service:latest
        imagePullPolicy: Always
        name: posts
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30